### ISSUE TITLE
Fix the IPSec ESP analyzer id check

### ISSUE THREAD

**Issue by keithjjones** [corelight/zeek-spicy-ipsec#2]
https://github.com/corelight/zeek-spicy-ipsec/blob/b327758bc24a8b9813f52b649520662281ac2804/analyzer/main.zeek#L889

This is useless because a packet analyzer doesn't use the confirm.  I didn't think of that when I put it in.  

There will have to be a warning about handling the ESP packet as it will be expensive for big IPSec site to site networks.

**Comment by awelzel** [comment]
@keithjjones  - I was looking at the code around this and you kept the option `disable_analyzer_after_detection` around, but it seems unused. That's fairly confusing if one expects the option to work and not looking at the implementation. Maybe you should remove the option as well?
```
	## Set to true to disable the analyzer after the protocol is confirmed.
	## This helps reduce processing if you will not look at all of the IPSec
	## traffic.
	option disable_analyzer_after_detection = F;
```
https://github.com/corelight/zeek-spicy-ipsec/blob/master/analyzer/main.zeek#L9

**Comment by keithjjones** [comment]
Fixed, thanks!
