### ISSUE TITLE
Test suite fails with zeek-4.2.0

### ISSUE THREAD

**Issue by bbannier** [corelight/zeek-spicy-ipsec#4]
While trying to install this package with `zkg` in an env with zeek-4.2.0 the installation failed due to a test failure:

```
analyzer.ike-zero-length ...
  > zeek -C -r ${TRACES}/ipsec-ikev1-zero-length.pcap %INPUT
  > test ! -s .stderr
... analyzer.ike-zero-length failed
  % 'test ! -s .stderr' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in /private/tmp/zeek-spicy-ipsec/tests/../analyzer/./main.zeek, line 877: deprecated (protocol_confirmation): Remove in v5.1. Use analyzer_confirmation.

analyzer.ikev1-payload-bad-length ...
  > zeek -C -r ${TRACES}/ipsec-ikev1-payload-bad-length.pcap %INPUT
  > test ! -s .stderr
... analyzer.ikev1-payload-bad-length failed
  % 'test ! -s .stderr' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in /private/tmp/zeek-spicy-ipsec/tests/../analyzer/./main.zeek, line 877: deprecated (protocol_confirmation): Remove in v5.1. Use analyzer_confirmation.
```

**Comment by bbannier** [comment]
I have excluded this package from [zeek/spicy-analyzers with spicy-analyzers-0.2.30](https://github.com/zeek/spicy-analyzers/blob/main/zkg.meta#L17-L18) so users can still install that metapackage in zeek-4.2 environments.

I'd be happy to include it again if this issue is fixed.

**Comment by bbannier** [comment]
Thanks for the reply. I did indeed run into more issues with the other analyzers as well, so following your suggestion I dropped them with spicy-analyzers-0.2.31.

**Comment by bbannier** [comment]
> Sorry, can't currently change this as it doesn't work on my macbook, where I dev and also run tests. I currently run Zeek v4.1.1 and Spicy plugin v1.3.7 for all my dev:
> 
> ```
> $ cmake --build .
> [ 50%] Compiling IPSEC analyzer
> [error] /[REDACTED]/Source/zeek-spicy-ipsec/analyzer/zeek_analyzer.spicy:9:2: unknown ID 'zeek::analyzer_confirmation'
> [error] /[REDACTED]/Source/zeek-spicy-ipsec/analyzer/zeek_analyzer.spicy:13:2: unknown ID 'zeek::analyzer_confirmation'
> [error] <Spicy Plugin for Zeek>: aborting after errors
> make[2]: *** [spicy-modules/ipsec.hlto] Error 1
> make[1]: *** [analyzer/CMakeFiles/IPSEC.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> I don't see any documentation here about this new function: https://docs.zeek.org/projects/spicy/en/latest/zeek.html#controlling-zeek-from-spicy

Like I had written in the original title, this is an issue with the zeek-4.2.0 API where `protocol_conformation` [became deprecated](https://github.com/zeek/zeek/blob/ce38609161cfd10a67cad301e60b7d96e3333835/NEWS#L173-L177). This cannot be fixed by editing Spicy source files. The issue is in your `main.zeek` file,

```
warning in /private/tmp/zeek-spicy-ipsec/tests/../analyzer/./main.zeek, line 877: deprecated (protocol_confirmation): Remove in v5.1. Use analyzer_confirmation.
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If you would like to you could probably work around this by doing a version check in with `@if ...` in your `main.zeek` file. Alternatively, you could make the test less strict about non-fatal errors on stderr.

**Comment by keithjjones** [comment]
The original information and title was not clear to me.  It still is not.  The error seemed to imply everything is changing from protocol_confirmation to analyzer_confirmation in v5 of Zeek.  Since Zeek is controlled by Spicy via the link I shared with you, won't the functions be changing in Spicy too?  Or will it continue to stay inconsistent with Zeek's new naming of the functions?

```
- The ``protocol_confirmation`` and ``protocol_violation`` events along with the
  corresponding ``Analyzer::ProtocolConfirmation` and
  ``Analyzer::ProtocolViolation`` C++ methods are marked as deprecated. They are
  replaced by ``analyzer_confirmation`` and ``analyzer_violation`` which can
  also now be implemented in packet analyzers.
```

This also sounds like everything "protocol_confirmation" is now "analyzer_confirmation" starting in v5.

I'll kill off the .stderr check on the tests.  That's an easy fix.

**Comment by bbannier** [comment]
> The error seemed to imply everything is changing from protocol_confirmation to analyzer_confirmation in v5 of Zeek.

That is correct. Since the current version of is zeek-4.2.0 `procotol_confirmation` is marked `&deprecated`, but is slated for removal with zeek-5.0.0.

> Since Zeek is controlled by Spicy via the link I shared with you, won't the functions be changing in Spicy too?

Zeek is not controlled by Spicy. For this package, spicy-plugin wraps you Spicy analyzer in a Zeek analyzer and loads it. Zeek is then running the script from this package which e.g., reacts to events from that analyzer.

Functions like e.g., [zeek::confirm_protocol](https://docs.zeek.org/projects/spicy/en/latest/zeek.html#spicy-confirm-protocol) trigger events in Zeek. Your `main.zeek` file implements e.g., `protocol_confirmation` which hooks into one such event.


> Or will it continue to stay inconsistent with Zeek's new naming of the functions?
> 
> ```
> - The ``protocol_confirmation`` and ``protocol_violation`` events along with the
>   corresponding ``Analyzer::ProtocolConfirmation` and
>   ``Analyzer::ProtocolViolation`` C++ methods are marked as deprecated. They are
>   replaced by ``analyzer_confirmation`` and ``analyzer_violation`` which can
>   also now be implemented in packet analyzers.
> ```
> 
> This also sounds like everything "protocol_confirmation" is now "analyzer_confirmation" starting in v5.

The function in spicy-plugin is called `confirm_protocol`, the Zeek event is `protocol_confirmation`. They are related, but not the same thing.

**Comment by keithjjones** [comment]
Thanks for the clarification, that helped.
